---
- name: install munin-node
  hosts: munin-node
  user: root

  roles:
    - epel-repos
    - munin-node
- name: install munin-host
  hosts: munin-host
  user: root

  roles:
    - epel-repos
    - nginx-repos
    - munin-host
